#开发配置:
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ohl?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #mysql5用com.mysql.jdbc.Driver,6+ 用com.mysql.cj.jdbc.Driver
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: dataplatform


#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.chen.library.**.entity
  mapperLocations: classpath:com/chen/library/**/mapper/*.xml


thymeleaf:
  mode: HTML
  cache: false
  encoding: utf-8
  enabled: true
  prefix: classpath:/templates/
  suffix: .html

server:
  port: 8087


    